[package]
name = "proiect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
zip = "0.6"
chrono = "0.4.31"
ftp = "3.0.1"
clap = { version = "4", features = ["derive"] }